DISEASE_INFO = {
    "english": {
        "cassava_bacterial_blight": {
            "description": "A bacterial disease that causes leaf wilting, angular spots, and stem lesions in cassava.",
            "treatment": "Remove severely infected leaves and plants immediately\nApply copper-based fungicide (like copper sulfate) every 10-14 days\nUse neem oil spray as a natural alternative\nAvoid moving infected cuttings to new fields",
            "prevention": "Use clean planting materials, maintain field hygiene, and rotate crops where possible.",
            "urgency": "high",
        },
        "cassava_brown_streak_disease": {
            "description": "A viral disease that can reduce cassava root quality and yield.",
            "treatment": "Remove infected plants and avoid replanting infected stems. No chemical cure available for viral diseases.",
            "prevention": "Use certified healthy cuttings and monitor fields regularly for symptoms.",
            "urgency": "high",
        },
        "cassava_green_mite": {
            "description": "A pest problem that damages cassava leaves and reduces plant vigor.",
            "treatment": "Apply neem oil spray every 7-10 days\nUse pyrethrum-based insecticides for severe infestations\nApply systemic insecticides like imidacloprid if recommended locally\nConsult local extension officers for safe control methods",
            "prevention": "Monitor early, maintain plant health, and use resistant varieties where available.",
            "urgency": "medium",
        },
        "cassava_mosaic_disease": {
            "description": "A viral disease that causes mosaic patterns and leaf distortion in cassava.",
            "treatment": "Remove affected plants immediately\nUse certified virus-free planting materials\nApply neem oil spray to reduce whitefly vectors\nNo chemical cure available for viral diseases",
            "prevention": "Plant resistant varieties and use disease-free cuttings.",
            "urgency": "high",
        },
        "cassava_healthy": {
            "description": "The cassava leaf appears healthy.",
            "treatment": "No treatment needed.",
            "prevention": "Continue good farm hygiene and regular monitoring.",
            "urgency": "low",
        },
        "maize_cercospora_leaf_spot": {
            "description": "A fungal disease causing rectangular lesions and reduced photosynthetic area.",
            "treatment": "Remove badly affected leaves and apply appropriate fungicide\nUse copper-based fungicides as a primary treatment\nApply neem oil or baking soda spray as natural alternatives\nSpray every 10-14 days during wet seasons",
            "prevention": "Use resistant varieties, rotate crops, and avoid overhead irrigation where possible.",
            "urgency": "medium",
        },
        "maize_common_rust": {
            "description": "A fungal disease that appears as rusty pustules on maize leaves.",
            "treatment": "Use sulfur-based fungicides as a primary treatment\nApply copper-based fungicides as an alternative option\nSpray at the first sign of disease, repeat every 10-14 days\nUse higher rates during wet, humid conditions",
            "prevention": "Plant resistant varieties and monitor fields early.",
            "urgency": "medium",
        },
        "maize_northern_leaf_blight": {
            "description": "A fungal disease causing long gray-green lesions on maize leaves.",
            "treatment": "Apply copper-based fungicides as primary treatment\nUse sulfur dust or wettable sulfur as an alternative\nRemove heavily infected debris and apply fungicide preventively\nSpray every 7-10 days during disease-favorable conditions",
            "prevention": "Rotate crops and use resistant maize varieties.",
            "urgency": "high",
        },
        "maize_healthy": {
            "description": "The maize leaf appears healthy.",
            "treatment": "No treatment needed.",
            "prevention": "Maintain regular inspection and balanced crop nutrition.",
            "urgency": "low",
        },
        "pepper_bacterial_spot": {
            "description": "A bacterial disease causing dark, water-soaked spots on pepper leaves.",
            "treatment": "Remove infected leaves and avoid handling wet plants\nApply copper-based bactericides like copper sulfate\nUse neem oil spray as a natural preventive treatment\nSpray every 7-10 days during wet weather",
            "prevention": "Use clean seeds, avoid overhead irrigation, and disinfect tools.",
            "urgency": "medium",
        },
        "pepper_healthy": {
            "description": "The pepper leaf appears healthy.",
            "treatment": "No treatment needed.",
            "prevention": "Keep monitoring and maintain field sanitation.",
            "urgency": "low",
        },
        "tomato_early_blight": {
            "description": "A fungal disease causing concentric brown spots on tomato leaves.",
            "treatment": "Prune infected leaves and apply suitable fungicide\nUse copper-based fungicides (copper sulfate) as primary treatment\nApply neem oil or baking soda spray as natural alternatives\nUse sulfur dust for powdery mildew prevention\nSpray every 7-10 days, starting at first sign of disease",
            "prevention": "Avoid wet foliage, rotate crops, and space plants well.",
            "urgency": "medium",
        },
        "tomato_late_blight": {
            "description": "A serious disease that can rapidly destroy tomato foliage and fruits.",
            "treatment": "Remove infected plants promptly and seek urgent local disease-control advice\nApply copper-based fungicides immediately\nUse neem oil spray as a natural supplement\nSpray every 5-7 days during wet, cool weather",
            "prevention": "Avoid prolonged leaf wetness and use preventive management practices.",
            "urgency": "high",
        },
        "tomato_mosaic_virus": {
            "description": "A viral disease causing mottled leaves and reduced plant growth.",
            "treatment": "Remove infected plants immediately\nApply neem oil spray to reduce aphid vectors\nUse insecticidal soap for pest control\nNo chemical cure available for viral diseases",
            "prevention": "Disinfect tools and wash hands after handling plants.",
            "urgency": "high",
        },
        "tomato_septoria_leaf_spot": {
            "description": "A fungal disease causing many small circular spots on tomato leaves.",
            "treatment": "Remove lower infected leaves and improve air circulation\nApply copper-based fungicides as primary treatment\nUse neem oil spray for natural control\nSpray every 7-10 days, focusing on lower leaves first\nCombine with cultural practices for best results",
            "prevention": "Avoid splash irrigation and rotate crops.",
            "urgency": "medium",
        },
        "tomato_target_spot": {
            "description": "A fungal disease causing brown lesions that may expand on leaves.",
            "treatment": "Remove infected leaves and use appropriate fungicide\nApply copper-based fungicides as primary treatment\nUse neem oil or baking soda spray as natural alternatives\nSpray every 7-14 days depending on disease pressure\nStart applications preventively in humid conditions",
            "prevention": "Improve spacing and reduce leaf wetness.",
            "urgency": "medium",
        },
        "tomato_yellow_leaf_curl_virus": {
            "description": "A viral disease causing upward leaf curling and yellowing.",
            "treatment": "Remove infected plants immediately\nApply neem oil spray to control whitefly vectors\nUse insecticidal soap for whitefly management\nUse systemic insecticides like imidacloprid if severe",
            "prevention": "Use resistant varieties and control whiteflies early.",
            "urgency": "high",
        },
        "tomato_healthy": {
            "description": "The tomato leaf appears healthy.",
            "treatment": "No treatment needed.",
            "prevention": "Continue good irrigation and disease monitoring practices.",
            "urgency": "low",
        },
    },
    "pidgin": {
        "cassava_bacterial_blight": {
            "description": "Bacterial disease wey dey cause cassava leaf to dry, angular spots, and stem lesions.",
            "treatment": "Remove leaves and plants wey don infect well well. No dey carry infected cuttings go new farm.",
            "prevention": "Use clean planting materials, keep farm clean, and rotate crops if possible.",
            "urgency": "high",
        },
        "cassava_brown_streak_disease": {
            "description": "Viral disease wey fit reduce cassava root quality and yield.",
            "treatment": "Remove infected plants and no dey replant infected stems.",
            "prevention": "Use certified healthy cuttings and dey monitor farm regularly for symptoms.",
            "urgency": "high",
        },
        "cassava_green_mite": {
            "description": "Pest problem wey dey damage cassava leaves and reduce plant strength.",
            "treatment": "Prune leaves wey don affect well and consult local extension officers for safe control methods.",
            "prevention": "Monitor early, maintain plant health, and use resistant varieties if available.",
            "urgency": "medium",
        },
        "cassava_mosaic_disease": {
            "description": "Viral disease wey dey cause mosaic patterns and leaf distortion for cassava.",
            "treatment": "Remove affected plants if possible and no dey use infected stems for propagation.",
            "prevention": "Plant resistant varieties and use disease-free cuttings.",
            "urgency": "high",
        },
        "cassava_healthy": {
            "description": "The cassava leaf dey healthy.",
            "treatment": "No treatment needed.",
            "prevention": "Continue good farm hygiene and regular monitoring.",
            "urgency": "low",
        },
        "maize_cercospora_leaf_spot": {
            "description": "Fungal disease wey dey cause rectangular lesions and reduce photosynthetic area.",
            "treatment": "Remove leaves wey don affect badly and apply appropriate fungicide if local people advise.",
            "prevention": "Use resistant varieties, rotate crops, and avoid overhead irrigation if possible.",
            "urgency": "medium",
        },
        "maize_common_rust": {
            "description": "Fungal disease wey dey appear as rusty pustules for maize leaves.",
            "treatment": "Use recommended fungicide if the infection dey severe and economically significant.",
            "prevention": "Plant resistant varieties and monitor fields early.",
            "urgency": "medium",
        },
        "maize_northern_leaf_blight": {
            "description": "Fungal disease wey dey cause long gray-green lesions for maize leaves.",
            "treatment": "Remove heavily infected debris and use proper disease management advice from extension workers.",
            "prevention": "Rotate crops and use resistant maize varieties.",
            "urgency": "high",
        },
        "maize_healthy": {
            "description": "The maize leaf dey healthy.",
            "treatment": "No treatment needed.",
            "prevention": "Maintain regular inspection and balanced crop nutrition.",
            "urgency": "low",
        },
        "pepper_bacterial_spot": {
            "description": "Bacterial disease wey dey cause dark, water-soaked spots for pepper leaves.",
            "treatment": "Remove infected leaves and avoid handling wet plants.",
            "prevention": "Use clean seeds, avoid overhead irrigation, and disinfect tools.",
            "urgency": "medium",
        },
        "pepper_healthy": {
            "description": "The pepper leaf dey healthy.",
            "treatment": "No treatment needed.",
            "prevention": "Keep monitoring and maintain field sanitation.",
            "urgency": "low",
        },
        "tomato_early_blight": {
            "description": "Fungal disease wey dey cause concentric brown spots for tomato leaves.",
            "treatment": "Prune infected leaves and apply suitable fungicide\nUse copper-based fungicides (copper sulfate) as primary treatment\nApply neem oil or baking soda spray as natural alternatives\nUse sulfur dust for powdery mildew prevention\nSpray every 7-10 days from first sign of disease",
            "prevention": "Avoid wet foliage, rotate crops, and space plants well.",
            "urgency": "medium",
        },
        "tomato_late_blight": {
            "description": "Serious disease wey fit quickly destroy tomato foliage and fruits.",
            "treatment": "Remove infected plants quickly and seek urgent local disease-control advice\nApply copper-based fungicides immediately\nUse neem oil spray as a natural supplement\nSpray every 5-7 days during wet, cool weather",
            "prevention": "Avoid prolonged leaf wetness and use preventive management practices.",
            "urgency": "high",
        },
        "tomato_mosaic_virus": {
            "description": "Viral disease wey dey cause mottled leaves and reduce plant growth.",
            "treatment": "Remove infected plants immediately\nApply neem oil spray to reduce aphid vectors\nUse insecticidal soap for pest control\nNo chemical cure available for viral diseases",
            "prevention": "Disinfect tools and wash hands after handling plants.",
            "urgency": "high",
        },
        "tomato_septoria_leaf_spot": {
            "description": "Fungal disease wey dey cause many small circular spots for tomato leaves.",
            "treatment": "Remove lower infected leaves and improve air circulation\nApply copper-based fungicides as primary treatment\nUse neem oil spray for natural control\nSpray every 7-10 days, focusing on lower leaves first\nCombine with cultural practices for best results",
            "prevention": "Avoid splash irrigation and rotate crops.",
            "urgency": "medium",
        },
        "tomato_target_spot": {
            "description": "Fungal disease wey dey cause brown lesions wey fit expand for leaves.",
            "treatment": "Remove infected leaves and use appropriate fungicide if necessary.",
            "prevention": "Improve spacing and reduce leaf wetness.",
            "urgency": "medium",
        },
        "tomato_yellow_leaf_curl_virus": {
            "description": "Viral disease wey dey cause upward leaf curling and yellowing.",
            "treatment": "Remove infected plants and manage whitefly vectors.",
            "prevention": "Use resistant varieties and control whiteflies early.",
            "urgency": "high",
        },
        "tomato_healthy": {
            "description": "The tomato leaf dey healthy.",
            "treatment": "No treatment needed.",
            "prevention": "Continue good irrigation and disease monitoring practices.",
            "urgency": "low",
        },
    },
    "yoruba": {
        "cassava_bacterial_blight": {
            "description": "Arun bacterial ti o n fa ki ewe cassava rọ, awọn aaye angular, ati awọn lesions igi.",
            "treatment": "Yọ awọn ewe ati awọn irugbin ti o ti ni akoran pupọ. Maṣe gbe awọn cuttings ti o ni akoran lọ si awọn oko tuntun.",
            "prevention": "Lo awọn ohun elo dida ti o mọ, tọju imototo oko, ki o si yi awọn irugbin pada nibiti o ba ṣeeṣe.",
            "urgency": "high",
        },
        "cassava_brown_streak_disease": {
            "description": "Arun viral ti o le dinku didara ati ikore gbongbo cassava.",
            "treatment": "Yọ awọn irugbin ti o ni akoran ki o maṣe tun gbin awọn stems ti o ni akoran.",
            "prevention": "Lo awọn cuttings ti o ni ilera ti a fọwọsi ki o si tọju awọn oko nigbagbogbo fun awọn ami aisan.",
            "urgency": "high",
        },
        "cassava_green_mite": {
            "description": "Iṣoro kokoro ti o n ba awọn ewe cassava jẹ ti o si n dinku agbara irugbin.",
            "treatment": "Ge awọn ewe ti o ni ipa pupọ ki o si kan si awọn oṣiṣẹ itẹsiwaju agbegbe fun awọn ọna iṣakoso ailewu.",
            "prevention": "Ṣe akiyesi ni kutukutu, tọju ilera irugbin, ki o si lo awọn orisi ti o ni resistance nibiti o ba wa.",
            "urgency": "medium",
        },
        "cassava_mosaic_disease": {
            "description": "Arun viral ti o n fa awọn ilana mosaic ati idarudapo ewe ni cassava.",
            "treatment": "Yọ awọn irugbin ti o ni ipa nibiti o ba ṣeeṣe ki o maṣe lo awọn stems ti o ni akoran fun itankale.",
            "prevention": "Gbin awọn orisi ti o ni resistance ki o si lo awọn cuttings ti ko ni arun.",
            "urgency": "high",
        },
        "cassava_healthy": {
            "description": "Ewe cassava naa wa ni ilera.",
            "treatment": "Ko nilo itọju.",
            "prevention": "Tẹsiwaju imototo oko ti o dara ati akiyesi deede.",
            "urgency": "low",
        },
        "maize_cercospora_leaf_spot": {
            "description": "Arun fungal ti o n fa awọn lesions onigun mẹrin ti o si n dinku agbegbe photosynthetic.",
            "treatment": "Yọ awọn ewe ti o ni ipa buburu ki o si lo fungicide ti o yẹ ti awọn eniyan agbegbe ba gba ni imọran.",
            "prevention": "Lo awọn orisi ti o ni resistance, yi awọn irugbin pada, ki o si yago fun irrigation lori ori nibiti o ba ṣeeṣe.",
            "urgency": "medium",
        },
        "maize_common_rust": {
            "description": "Arun fungal ti o n han bi awọn pustules ipata lori awọn ewe maize.",
            "treatment": "Lo fungicide ti a ṣe iṣeduro ti akoran naa ba le pupọ ati pataki ni ọrọ eto-ọrọ.",
            "prevention": "Gbin awọn orisi ti o ni resistance ki o si tọju awọn oko ni kutukutu.",
            "urgency": "medium",
        },
        "maize_northern_leaf_blight": {
            "description": "Arun fungal ti o n fa awọn lesions gigun gray-green lori awọn ewe maize.",
            "treatment": "Yọ awọn debris ti o ni akoran pupọ ki o si lo imọran iṣakoso arun ti o yẹ lati ọdọ awọn oṣiṣẹ itẹsiwaju.",
            "prevention": "Yi awọn irugbin pada ki o si lo awọn orisi maize ti o ni resistance.",
            "urgency": "high",
        },
        "maize_healthy": {
            "description": "Ewe maize wa ni ilera.",
            "treatment": "Ko nilo itọju.",
            "prevention": "Ṣetọju akiyesi deede ati onjẹ irugbin ti o ni iwọntunwọnsi.",
            "urgency": "low",
        },
        "pepper_bacterial_spot": {
            "description": "Arun bacterial ti o n fa awọn aaye dudu, ti omi ti kun lori awọn ewe ata.",
            "treatment": "Yọ awọn ewe ti o ni akoran ki o si yago fun mimu awọn irugbin tutu.",
            "prevention": "Lo awọn irugbin ti o mọ, yago fun irrigation lori ori, ki o si disinfect awọn irinṣẹ.",
            "urgency": "medium",
        },
        "pepper_healthy": {
            "description": "Ewe ata wa ni ilera.",
            "treatment": "Ko nilo itọju.",
            "prevention": "Tẹsiwaju akiyesi ki o si tọju imototo oko.",
            "urgency": "low",
        },
        "tomato_early_blight": {
            "description": "Arun fungal ti o n fa awọn aaye brown concentric lori awọn ewe tomato.",
            "treatment": "Ge awọn ewe ti o ni akoran ki o si lo fungicide ti o yẹ\nLo awọn fungicides ti o da lori copper (copper sulfate) gẹgẹbi itọju akọkọ\nLo neem oil tabi baking soda spray gẹgẹbi awọn yiyan adayeba\nLo sulfur dust fun idena powdery mildew\nFun ororo ni gbogbo ọjọ 7-10 lati ami akọkọ ti arun",
            "prevention": "Yago fun foliage tutu, yi awọn irugbin pada, ki o si fi awọn irugbin si aaye daradara.",
            "urgency": "medium",
        },
        "tomato_late_blight": {
            "description": "Arun to le ti o le pa foliage ati awọn eso tomato run.",
            "treatment": "Yọ awọn irugbin ti o ni akoran ni kiakia ki o si wa imọran iṣakoso arun agbegbe ni iyara\nLo awọn fungicides ti o da lori copper lẹsẹkẹsẹ\nLo neem oil spray gẹgẹbi afikun adayeba\nFun ororo ni gbogbo ọjọ 5-7 nigba oju ojo tutu",
            "prevention": "Yago fun wetness ewe gigun ki o si lo awọn iṣe iṣakoso idena.",
            "urgency": "high",
        },
        "tomato_mosaic_virus": {
            "description": "Arun viral ti o n fa awọn ewe mottled ati dinku idagbasoke irugbin.",
            "treatment": "Yọ awọn irugbin ti o ni akoran lẹsẹkẹsẹ\nLo neem oil spray lati dinku awọn vectors aphid\nLo insecticidal soap fun iṣakoso kokoro\nKo si oogun kemikali ti o wa fun awọn arun viral",
            "prevention": "Disinfect awọn irinṣẹ ki o si fo ọwọ lẹhin mimu awọn irugbin.",
            "urgency": "high",
        },
        "tomato_septoria_leaf_spot": {
            "description": "Arun fungal ti o n fa ọpọlọpọ awọn aaye circular kekere lori awọn ewe tomato.",
            "treatment": "Yọ awọn ewe ti o ni akoran ni isalẹ ki o si mu afẹfẹ dara si\nLo awọn fungicides ti o da lori copper gẹgẹbi itọju akọkọ\nLo neem oil spray fun iṣakoso adayeba\nFun ororo ni gbogbo ọjọ 7-10, ni idojukọ awọn ewe isalẹ akọkọ\nDarapọ pẹlu awọn iṣe aṣa fun awọn abajade ti o dara julọ",
            "prevention": "Yago fun irrigation splash ki o si yi awọn irugbin pada.",
            "urgency": "medium",
        },
        "tomato_target_spot": {
            "description": "Arun fungal ti o n fa awọn lesions brown ti o le gbooro lori awọn ewe.",
            "treatment": "Yọ awọn ewe ti o ni akoran ki o si lo fungicide ti o yẹ\nLo awọn fungicides ti o da lori copper gẹgẹbi itọju akọkọ\nLo neem oil tabi baking soda spray gẹgẹbi awọn yiyan adayeba\nFun ororo ni gbogbo ọjọ 7-14 da lori titẹ arun\nBẹrẹ awọn ohun elo idena ni awọn ipo ọriniinitutu",
            "prevention": "Mu aaye dara si ki o si dinku wetness ewe.",
            "urgency": "medium",
        },
        "tomato_yellow_leaf_curl_virus": {
            "description": "Arun viral ti o n fa curling ewe si oke ati yellowing.",
            "treatment": "Yọ awọn irugbin ti o ni akoran ki o si ṣakoso awọn whitefly vectors.",
            "prevention": "Lo awọn orisi ti o ni resistance ki o si ṣakoso whiteflies ni kutukutu.",
            "urgency": "high",
        },
        "tomato_healthy": {
            "description": "Ewe tomato wa ni ilera.",
            "treatment": "Ko nilo itọju.",
            "prevention": "Tẹsiwaju irrigation ti o dara ati awọn iṣe akiyesi arun.",
            "urgency": "low",
        },
    }
}


def get_advice(label: str, language: str = "english") -> dict:
    lang_data = DISEASE_INFO.get(language.lower(), DISEASE_INFO["english"])
    return lang_data.get(label, {
        "description": "No advice available for this class yet.",
        "treatment": "Consult a local agricultural extension officer.",
        "prevention": "Monitor the crop closely.",
        "urgency": "unknown",
    })